### ISSUE TITLE
Specification of package description format

### ISSUE THREAD

**Issue by samvv** [CPkgs/CPkg#1]
We need to come up with a nice and friendly format that is both easy to modify programmatically and by the user if he or she needs to.

 - Some package managers (such as [npm](https://npmjs.com)) use a simple JSON-format that meets these criteria. Most languages, including C++, have libraries for handling JSON data. On the other hand, it is easy to make a syntax error and some might not like it that there is no posibility to add comments.
 - Elixir and Ruby use a DSL that makes it difficult to edit it programmatically, but that does make it easier for the developer to edit the configuration and use the full Elixir programming language inside the configuration file.

Right now, I'm inclined to use a JSON-format because it is easiest to implement and forces metadata to be fully static and thus easily processed by third-party tools.

**Comment by samvv** [comment]
For now, we will use something similar to the following:

```
name: my-package-name
version: 0.0.1-alpha2
artifacts:
- name: foo
  include-dirs:
  - include/
  sources:
  - src/foo.cpp
- name: bar
  include-dirs:
  - include/
  sources:
  - src/bar.cpp
```

This will suffice for the most simple use cases.
